package services.oasis.ubl.ordering.orderingprocess.buyerparty.cancelorder;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sat Oct 30 21:01:34 BRST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/cancelOrder", name = "UBL_OrderingProcess_BuyerParty_CancelOrder")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.orderresponse_2.ObjectFactory.class, ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.ordercancellation_2.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class})
public interface UBLOrderingProcessBuyerPartyCancelOrder extends ServiceAccessContract {

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/cancelOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.cancelorder.Alive")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/cancelOrder/alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/cancelOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.cancelorder.AliveResponse")
    public java.lang.Boolean alive();

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "cancelOrder", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/cancelOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.cancelorder.CancelOrder")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/cancelOrder/cancelOrder")
    @ResponseWrapper(localName = "cancelOrderResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/cancelOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.cancelorder.CancelOrderResponse")
    public oasis.names.specification.ubl.schema.xsd.ordercancellation_2.OrderCancellationType cancelOrder(
        @WebParam(name = "inputOrderResponseSimple", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.OrderResponseSimpleType inputOrderResponseSimple,
        @WebParam(name = "inputOrderResponse", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponse_2.OrderResponseType inputOrderResponse
    );

    @Oneway
    @RequestWrapper(localName = "cancelOrderAsync", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/cancelOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.cancelorder.CancelOrderAsync")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/cancelOrder/cancelOrderAsync")
    public void cancelOrderAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "inputOrderResponseSimple", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.OrderResponseSimpleType inputOrderResponseSimple,
        @WebParam(name = "inputOrderResponse", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponse_2.OrderResponseType inputOrderResponse
    );
}
