package services.oasis.ubl.payment.paymentprocess.accountingcustomer.notifyofpayment;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sat Oct 30 17:33:15 BRST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/notifyOfPayment", name = "UBL_PaymentProcess_AccountingCustomer_NotifyOfPayment")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.remittanceadvice_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class, ObjectFactory.class})
public interface UBLPaymentProcessAccountingCustomerNotifyOfPayment extends ServiceAccessContract {

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "notifyOfPayment", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/notifyOfPayment", className = "services.oasis.ubl.payment.paymentprocess.accountingcustomer.notifyofpayment.NotifyOfPayment")
    @WebMethod(action = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/notifyOfPayment/notifyOfPayment")
    @ResponseWrapper(localName = "notifyOfPaymentResponse", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/notifyOfPayment", className = "services.oasis.ubl.payment.paymentprocess.accountingcustomer.notifyofpayment.NotifyOfPaymentResponse")
    public oasis.names.specification.ubl.schema.xsd.remittanceadvice_2.RemittanceAdviceType notifyOfPayment();

    @Oneway
    @RequestWrapper(localName = "notifyOfPaymentAsync", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/notifyOfPayment", className = "services.oasis.ubl.payment.paymentprocess.accountingcustomer.notifyofpayment.NotifyOfPaymentAsync")
    @WebMethod(action = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/notifyOfPayment/notifyOfPaymentAsync")
    public void notifyOfPaymentAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext
    );

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/notifyOfPayment", className = "services.oasis.ubl.payment.paymentprocess.accountingcustomer.notifyofpayment.Alive")
    @WebMethod(action = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/notifyOfPayment/alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/notifyOfPayment", className = "services.oasis.ubl.payment.paymentprocess.accountingcustomer.notifyofpayment.AliveResponse")
    public java.lang.Boolean alive();
}
