package services.oasis.ubl.payment.paymentprocess.accountingcustomer.authorizepayment;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sat Oct 30 17:33:02 BRST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/authorizePayment", name = "UBL_PaymentProcess_AccountingCustomer_AuthorizePayment")
@XmlSeeAlso({ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class})
public interface UBLPaymentProcessAccountingCustomerAuthorizePayment extends ServiceAccessContract {

    @Oneway
    @RequestWrapper(localName = "authorizePaymentAsync", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/authorizePayment", className = "services.oasis.ubl.payment.paymentprocess.accountingcustomer.authorizepayment.AuthorizePaymentAsync")
    @WebMethod(action = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/authorizePayment/authorizePaymentAsync")
    public void authorizePaymentAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext
    );

    @RequestWrapper(localName = "authorizePayment", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/authorizePayment", className = "services.oasis.ubl.payment.paymentprocess.accountingcustomer.authorizepayment.AuthorizePayment")
    @WebMethod(action = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/authorizePayment/authorizePayment")
    @ResponseWrapper(localName = "authorizePaymentResponse", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/authorizePayment", className = "services.oasis.ubl.payment.paymentprocess.accountingcustomer.authorizepayment.AuthorizePaymentResponse")
    public void authorizePayment();

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/authorizePayment", className = "services.oasis.ubl.payment.paymentprocess.accountingcustomer.authorizepayment.Alive")
    @WebMethod(action = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/authorizePayment/alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/authorizePayment", className = "services.oasis.ubl.payment.paymentprocess.accountingcustomer.authorizepayment.AliveResponse")
    public java.lang.Boolean alive();
}
