package services.oasis.ubl.payment.paymentprocess.accountingsupplier.notifypayee;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sat Oct 30 17:33:29 BRST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingSupplier/notifyPayee", name = "UBL_PaymentProcess_AccountingSupplier_NotifyPayee")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.remittanceadvice_2.ObjectFactory.class, ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class})
public interface UBLPaymentProcessAccountingSupplierNotifyPayee extends ServiceAccessContract {

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingSupplier/notifyPayee", className = "services.oasis.ubl.payment.paymentprocess.accountingsupplier.notifypayee.Alive")
    @WebMethod(action = "http://ubl.oasis.services/payment/paymentprocess/accountingSupplier/notifyPayee/alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingSupplier/notifyPayee", className = "services.oasis.ubl.payment.paymentprocess.accountingsupplier.notifypayee.AliveResponse")
    public java.lang.Boolean alive();

    @Oneway
    @RequestWrapper(localName = "notifyPayeeAsync", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingSupplier/notifyPayee", className = "services.oasis.ubl.payment.paymentprocess.accountingsupplier.notifypayee.NotifyPayeeAsync")
    @WebMethod(action = "http://ubl.oasis.services/payment/paymentprocess/accountingCustomer/notifyPayee/notifyPayeeAsync")
    public void notifyPayeeAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.remittanceadvice_2.RemittanceAdviceType input
    );

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "notifyPayee", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingSupplier/notifyPayee", className = "services.oasis.ubl.payment.paymentprocess.accountingsupplier.notifypayee.NotifyPayee")
    @WebMethod(action = "http://ubl.oasis.services/payment/paymentprocess/accountingSupplier/notifyPayee/notifyPayee")
    @ResponseWrapper(localName = "notifyPayeeResponse", targetNamespace = "http://ubl.oasis.services/payment/paymentprocess/accountingSupplier/notifyPayee", className = "services.oasis.ubl.payment.paymentprocess.accountingsupplier.notifypayee.NotifyPayeeResponse")
    public oasis.names.specification.ubl.schema.xsd.remittanceadvice_2.RemittanceAdviceType notifyPayee(
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.remittanceadvice_2.RemittanceAdviceType input
    );
}
