package services.oasis.ubl.ordering.orderingprocess.buyerparty.changeorder;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sat Oct 30 21:01:48 BRST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/changeOrder", name = "UBL_OrderingProcess_BuyerParty_ChangeOrder")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.orderresponse_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.orderchange_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class, ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class})
public interface UBLOrderingProcessBuyerPartyChangeOrder extends ServiceAccessContract {

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "changeOrder", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/changeOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.changeorder.ChangeOrder")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/changeOrder/changeOrder")
    @ResponseWrapper(localName = "changeOrderResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/changeOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.changeorder.ChangeOrderResponse")
    public oasis.names.specification.ubl.schema.xsd.orderchange_2.OrderChangeType changeOrder(
        @WebParam(name = "inputOrderResponseSimple", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.OrderResponseSimpleType inputOrderResponseSimple,
        @WebParam(name = "inputOrderResponse", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponse_2.OrderResponseType inputOrderResponse
    );

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/changeOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.changeorder.Alive")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/changeOrder/alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/changeOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.changeorder.AliveResponse")
    public java.lang.Boolean alive();

    @Oneway
    @RequestWrapper(localName = "changeOrderAsync", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/changeOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.changeorder.ChangeOrderAsync")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/changeOrder/changeOrderAsync")
    public void changeOrderAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "inputOrderResponseSimple", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.OrderResponseSimpleType inputOrderResponseSimple,
        @WebParam(name = "inputOrderResponse", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponse_2.OrderResponseType inputOrderResponse
    );
}
