package services.oasis.ubl.ordering.orderingprocess.buyerparty.placeorder;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sat Oct 30 21:02:03 BRST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/placeOrder", name = "UBL_OrderingProcess_BuyerParty_PlaceOrder")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.order_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class})
public interface UBLOrderingProcessBuyerPartyPlaceOrder extends ServiceAccessContract {

    @Oneway
    @RequestWrapper(localName = "placeOrderAsync", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/placeOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.placeorder.PlaceOrderAsync")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/placeOrder/placeOrderAsync")
    public void placeOrderAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext
    );

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/placeOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.placeorder.Alive")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/placeOrder/alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/placeOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.placeorder.AliveResponse")
    public java.lang.Boolean alive();

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "placeOrder", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/placeOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.placeorder.PlaceOrder")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/placeOrder/placeOrder")
    @ResponseWrapper(localName = "placeOrderResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/placeOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.placeorder.PlaceOrderResponse")
    public oasis.names.specification.ubl.schema.xsd.order_2.OrderType placeOrder();
}
