package services.oasis.ubl.ordering.orderingprocess.buyerparty.receiveresponse;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sat Oct 30 21:02:18 BRST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/receiveResponse", name = "UBL_OrderingProcess_BuyerParty_ReceiveResponse")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.orderresponse_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class, ObjectFactory.class})
public interface UBLOrderingProcessBuyerPartyReceiveResponse extends ServiceAccessContract {

    @RequestWrapper(localName = "receiveResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/receiveResponse", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.receiveresponse.ReceiveResponse")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/receiveResponse/receiveResponse")
    @ResponseWrapper(localName = "receiveResponseResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/receiveResponse", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.receiveresponse.ReceiveResponseResponse")
    public void receiveResponse(
        @WebParam(name = "inputOrderResponseSimple", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.OrderResponseSimpleType inputOrderResponseSimple,
        @WebParam(name = "inputOrderResponse", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponse_2.OrderResponseType inputOrderResponse,
        @WebParam(mode = WebParam.Mode.OUT, name = "outputOrderResponseSimple", targetNamespace = "")
        javax.xml.ws.Holder<oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.OrderResponseSimpleType> outputOrderResponseSimple,
        @WebParam(mode = WebParam.Mode.OUT, name = "outputOrderResponse", targetNamespace = "")
        javax.xml.ws.Holder<oasis.names.specification.ubl.schema.xsd.orderresponse_2.OrderResponseType> outputOrderResponse,
        @WebParam(mode = WebParam.Mode.OUT, name = "outputDecision", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> outputDecision
    );

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/receiveResponse", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.receiveresponse.Alive")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/receiveResponse/alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/receiveResponse", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.receiveresponse.AliveResponse")
    public java.lang.Boolean alive();

    @Oneway
    @RequestWrapper(localName = "receiveResponseAsync", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/receiveResponse", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.receiveresponse.ReceiveResponseAsync")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/receiveResponse/receiveResponseAsync")
    public void receiveResponseAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "inputOrderResponseSimple", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.OrderResponseSimpleType inputOrderResponseSimple,
        @WebParam(name = "inputOrderResponse", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponse_2.OrderResponseType inputOrderResponse
    );
}
