package services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.determineaction;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 28 20:49:03 BRT 2018
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/determineAction", name = "UBL_FulfilmentWithReceiptAdvice_BuyerParty_DetermineAction")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.order_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class})
public interface UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineAction extends ServiceAccessContract {

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/determineAction/determineAction")
    @RequestWrapper(localName = "determineAction", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/determineAction", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.determineaction.DetermineAction")
    @ResponseWrapper(localName = "determineActionResponse", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/determineAction", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.determineaction.DetermineActionResponse")
    public void determineAction(
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.order_2.OrderType input,
        @WebParam(mode = WebParam.Mode.OUT, name = "outputDocument", targetNamespace = "")
        javax.xml.ws.Holder<oasis.names.specification.ubl.schema.xsd.order_2.OrderType> outputDocument,
        @WebParam(mode = WebParam.Mode.OUT, name = "outputDecision", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> outputDecision
    );

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/determineAction/alive")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/determineAction", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.determineaction.Alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/determineAction", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.determineaction.AliveResponse")
    @WebResult(name = "output", targetNamespace = "")
    public java.lang.Boolean alive();

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/determineAction/determineActionAsync")
    @Oneway
    @RequestWrapper(localName = "determineActionAsync", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/determineAction", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.determineaction.DetermineActionAsync")
    public void determineActionAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.order_2.OrderType input
    );
}
