
/*
 * 
 */

package services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.determineaction;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 28 20:49:03 BRT 2018
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "UBL_FulfilmentWithReceiptAdvice_BuyerParty_DetermineActionService", 
                  wsdlLocation = "file:UBL_FulfilmentWithReceiptAdvice_BuyerParty_DetermineAction.wsdl",
                  targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/determineAction") 
public class UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineActionService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/determineAction", "UBL_FulfilmentWithReceiptAdvice_BuyerParty_DetermineActionService");
    public final static QName UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineActionServicePort = new QName("http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/determineAction", "UBL_FulfilmentWithReceiptAdvice_BuyerParty_DetermineActionServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:UBL_FulfilmentWithReceiptAdvice_BuyerParty_DetermineAction.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:UBL_FulfilmentWithReceiptAdvice_BuyerParty_DetermineAction.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineActionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineActionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineActionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineActionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineActionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineActionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineAction
     */
    @WebEndpoint(name = "UBL_FulfilmentWithReceiptAdvice_BuyerParty_DetermineActionServicePort")
    public UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineAction getUBLFulfilmentWithReceiptAdviceBuyerPartyDetermineActionServicePort() {
        return super.getPort(UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineActionServicePort, UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineAction.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineAction
     */
    @WebEndpoint(name = "UBL_FulfilmentWithReceiptAdvice_BuyerParty_DetermineActionServicePort")
    public UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineAction getUBLFulfilmentWithReceiptAdviceBuyerPartyDetermineActionServicePort(WebServiceFeature... features) {
        return super.getPort(UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineActionServicePort, UBLFulfilmentWithReceiptAdviceBuyerPartyDetermineAction.class, features);
    }

}
