package services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.checkstatusofitems;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 28 20:49:34 BRT 2018
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/checkStatusOfItems", name = "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_CheckStatusOfItems")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.order_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class})
public interface UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItems extends ServiceAccessContract {

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/checkStatusOfItems/checkStatusOfItems")
    @RequestWrapper(localName = "checkStatusOfItems", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/checkStatusOfItems", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.checkstatusofitems.CheckStatusOfItems")
    @ResponseWrapper(localName = "checkStatusOfItemsResponse", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/checkStatusOfItems", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.checkstatusofitems.CheckStatusOfItemsResponse")
    @WebResult(name = "output", targetNamespace = "")
    public oasis.names.specification.ubl.schema.xsd.order_2.OrderType checkStatusOfItems(
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.order_2.OrderType input
    );

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/checkStatusOfItems/checkStatusOfItemsAsync")
    @Oneway
    @RequestWrapper(localName = "checkStatusOfItemsAsync", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/checkStatusOfItems", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.checkstatusofitems.CheckStatusOfItemsAsync")
    public void checkStatusOfItemsAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.order_2.OrderType input
    );

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/checkStatusOfItems/alive")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/checkStatusOfItems", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.checkstatusofitems.Alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/checkStatusOfItems", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.checkstatusofitems.AliveResponse")
    @WebResult(name = "output", targetNamespace = "")
    public java.lang.Boolean alive();
}
