
/*
 * 
 */

package services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.checkstatusofitems;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 28 20:49:34 BRT 2018
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_CheckStatusOfItemsService", 
                  wsdlLocation = "file:UBL_FulfilmentWithReceiptAdvice_DeliveryParty_CheckStatusOfItems.wsdl",
                  targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/checkStatusOfItems") 
public class UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItemsService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/checkStatusOfItems", "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_CheckStatusOfItemsService");
    public final static QName UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItemsServicePort = new QName("http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/checkStatusOfItems", "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_CheckStatusOfItemsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:UBL_FulfilmentWithReceiptAdvice_DeliveryParty_CheckStatusOfItems.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:UBL_FulfilmentWithReceiptAdvice_DeliveryParty_CheckStatusOfItems.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItemsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItemsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItemsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItemsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItemsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItemsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItems
     */
    @WebEndpoint(name = "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_CheckStatusOfItemsServicePort")
    public UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItems getUBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItemsServicePort() {
        return super.getPort(UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItemsServicePort, UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItems.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItems
     */
    @WebEndpoint(name = "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_CheckStatusOfItemsServicePort")
    public UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItems getUBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItemsServicePort(WebServiceFeature... features) {
        return super.getPort(UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItemsServicePort, UBLFulfilmentWithReceiptAdviceDeliveryPartyCheckStatusOfItems.class, features);
    }

}
