package br.ufsc.gsigma.infrastructure.ws.context;

public interface ExecutionFlags {

	public static final String FLAG_DISABLE_RESILIENCE = "DISABLE_RESILIENCE";

	public static final String FLAG_DISABLE_SERVICE_CHECK = "DISABLE_SERVICE_CHECK";

	public static final String FLAG_DISABLE_SERVICE_DISCOVERY = "DISABLE_SERVICE_DISCOVERY";

	public static final String FLAG_DISABLE_SERVICE_MONITORING = "DISABLE_SERVICE_MONITORING";

	public static final String FLAG_DISABLE_ADHOC_SERVICE_DEPLOYMENT = "DISABLE_ADHOC_SERVICE_DEPLOYMENT";

	public static final String FLAG_IGNORE_DEPLOYED_SERVICES_CHECK = "IGNORE_DEPLOYED_SERVICES_CHECK";

	public static final String FLAG_IGNORE_QOS_CONSTRAINTS_SERVICE_DISCOVERY = "IGNORE_QOS_CONSTRAINTS_SERVICE_DISCOVERY";

	public static final String FLAG_IGNORE_EVENT_PUBLISHING = "IGNORE_EVENT_PUBLISHING";

	public static final String FLAG_RANDOM_SERVICE_PROTOCOL_CONVERTER = "RANDOM_SERVICE_PROTOCOL_CONVERTER";

	public static final String FLAG_FORCE_PROTOCOL_CONVERTER = "FORCE_PROTOCOL_CONVERTER";

}
