package br.ufsc.gsigma.infrastructure.ws.context;

public interface ExecutionAttributes {

	public static final String ATT_HTTP_REQUEST_INFO = "HTTP_REQUEST_INFO";

	public static final String ATT_LOG_ATTRS = "LOG_ATTRS";

	public static final String ATT_RESILIENCE_SERVICE_CHECK_HTTP_CONNECTION_TIMEOUT = "RESILIENCE_SERVICE_CHECK_HTTP_CONNECTION_TIMEOUT";

	public static final String ATT_RESILIENCE_SERVICE_CHECK_HTTP_READ_TIMEOUT = "RESILIENCE_SERVICE_CHECK_HTTP_READ_TIMEOUT";

	public static final String ATT_RESILIENCE_PLANNING_SCHEDULER_DELAY = "RESILIENCE_PLANNING_SCHEDULER_DELAY";

	public static final String ATT_DEPLOYMENT_SERVERS = "DEPLOYMENT_SERVERS";

	public static final String ATT_SERVICES_DECISIONS = "SERVICES_DECISIONS";

	public static final String ATT_DEPLOYMENT_ORCHESTRATOR_SERVERS = "DEPLOYMENT_ORCHESTRATOR_SERVERS";

	public static final String ATT_INFRASTRUCTURE_PROVIDER_ID = "INFRASTRUCTURE_PROVIDER_ID";

	public static final String ATT_BINDING_WAIT_FOR_NEW_BINDING_CONFIGURATION_TIMEOUT = "BINDING_WAIT_FOR_NEW_BINDING_CONFIGURATION_TIMEOUT";

	public static final String ATT_INVOKED_SERVICE_EXECUTION_DELAY = "INVOKED_SERVICE_EXECUTION_DELAY";

	public static final String ATT_PROTOCOL_CONVERTER = "PROTOCOL_CONVERTER";

}
