package services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.advisebuyerofstatus;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 28 20:49:24 BRT 2018
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/adviseBuyerOfStatus", name = "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_AdviseBuyerOfStatus")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.order_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class})
public interface UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatus extends ServiceAccessContract {

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/adviseBuyerOfStatus/alive")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/adviseBuyerOfStatus", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.advisebuyerofstatus.Alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/adviseBuyerOfStatus", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.advisebuyerofstatus.AliveResponse")
    @WebResult(name = "output", targetNamespace = "")
    public java.lang.Boolean alive();

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/adviseBuyerOfStatus/adviseBuyerOfStatus")
    @RequestWrapper(localName = "adviseBuyerOfStatus", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/adviseBuyerOfStatus", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.advisebuyerofstatus.AdviseBuyerOfStatus")
    @ResponseWrapper(localName = "adviseBuyerOfStatusResponse", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/adviseBuyerOfStatus", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.advisebuyerofstatus.AdviseBuyerOfStatusResponse")
    @WebResult(name = "output", targetNamespace = "")
    public oasis.names.specification.ubl.schema.xsd.order_2.OrderType adviseBuyerOfStatus(
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.order_2.OrderType input
    );

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/adviseBuyerOfStatus/adviseBuyerOfStatusAsync")
    @Oneway
    @RequestWrapper(localName = "adviseBuyerOfStatusAsync", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/adviseBuyerOfStatus", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.advisebuyerofstatus.AdviseBuyerOfStatusAsync")
    public void adviseBuyerOfStatusAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.order_2.OrderType input
    );
}
