
/*
 * 
 */

package services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.advisebuyerofstatus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 28 20:49:24 BRT 2018
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_AdviseBuyerOfStatusService", 
                  wsdlLocation = "file:UBL_FulfilmentWithReceiptAdvice_DeliveryParty_AdviseBuyerOfStatus.wsdl",
                  targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/adviseBuyerOfStatus") 
public class UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatusService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/adviseBuyerOfStatus", "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_AdviseBuyerOfStatusService");
    public final static QName UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatusServicePort = new QName("http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/adviseBuyerOfStatus", "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_AdviseBuyerOfStatusServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:UBL_FulfilmentWithReceiptAdvice_DeliveryParty_AdviseBuyerOfStatus.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:UBL_FulfilmentWithReceiptAdvice_DeliveryParty_AdviseBuyerOfStatus.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatusService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatusService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatusService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatusService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatusService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatusService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatus
     */
    @WebEndpoint(name = "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_AdviseBuyerOfStatusServicePort")
    public UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatus getUBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatusServicePort() {
        return super.getPort(UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatusServicePort, UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatus.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatus
     */
    @WebEndpoint(name = "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_AdviseBuyerOfStatusServicePort")
    public UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatus getUBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatusServicePort(WebServiceFeature... features) {
        return super.getPort(UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatusServicePort, UBLFulfilmentWithReceiptAdviceDeliveryPartyAdviseBuyerOfStatus.class, features);
    }

}
