
/*
 * 
 */

package services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.acceptitems;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 28 20:48:29 BRT 2018
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "UBL_FulfilmentWithReceiptAdvice_BuyerParty_AcceptItemsService", 
                  wsdlLocation = "file:UBL_FulfilmentWithReceiptAdvice_BuyerParty_AcceptItems.wsdl",
                  targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/acceptItems") 
public class UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItemsService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/acceptItems", "UBL_FulfilmentWithReceiptAdvice_BuyerParty_AcceptItemsService");
    public final static QName UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItemsServicePort = new QName("http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/acceptItems", "UBL_FulfilmentWithReceiptAdvice_BuyerParty_AcceptItemsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:UBL_FulfilmentWithReceiptAdvice_BuyerParty_AcceptItems.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:UBL_FulfilmentWithReceiptAdvice_BuyerParty_AcceptItems.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItemsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItemsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItemsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItemsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItemsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItemsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItems
     */
    @WebEndpoint(name = "UBL_FulfilmentWithReceiptAdvice_BuyerParty_AcceptItemsServicePort")
    public UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItems getUBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItemsServicePort() {
        return super.getPort(UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItemsServicePort, UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItems.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItems
     */
    @WebEndpoint(name = "UBL_FulfilmentWithReceiptAdvice_BuyerParty_AcceptItemsServicePort")
    public UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItems getUBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItemsServicePort(WebServiceFeature... features) {
        return super.getPort(UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItemsServicePort, UBLFulfilmentWithReceiptAdviceBuyerPartyAcceptItems.class, features);
    }

}
