package services.oasis.ubl.ordering.orderingprocess.sellerparty.processorderchange;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sat Oct 30 21:03:45 BRST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/processOrderChange", name = "UBL_OrderingProcess_SellerParty_ProcessOrderChange")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.orderchange_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.order_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class})
public interface UBLOrderingProcessSellerPartyProcessOrderChange extends ServiceAccessContract {

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/processOrderChange", className = "services.oasis.ubl.ordering.orderingprocess.sellerparty.processorderchange.Alive")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/processOrderChange/alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/processOrderChange", className = "services.oasis.ubl.ordering.orderingprocess.sellerparty.processorderchange.AliveResponse")
    public java.lang.Boolean alive();

    @RequestWrapper(localName = "processOrderChange", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/processOrderChange", className = "services.oasis.ubl.ordering.orderingprocess.sellerparty.processorderchange.ProcessOrderChange")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/processOrderChange/processOrderChange")
    @ResponseWrapper(localName = "processOrderChangeResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/processOrderChange", className = "services.oasis.ubl.ordering.orderingprocess.sellerparty.processorderchange.ProcessOrderChangeResponse")
    public void processOrderChange(
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderchange_2.OrderChangeType input,
        @WebParam(mode = WebParam.Mode.OUT, name = "outputDocument", targetNamespace = "")
        javax.xml.ws.Holder<oasis.names.specification.ubl.schema.xsd.order_2.OrderType> outputDocument,
        @WebParam(mode = WebParam.Mode.OUT, name = "outputDecision", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> outputDecision
    );

    @Oneway
    @RequestWrapper(localName = "processOrderChangeAsync", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/processOrderChange", className = "services.oasis.ubl.ordering.orderingprocess.sellerparty.processorderchange.ProcessOrderChangeAsync")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/processOrderChange/processOrderChangeAsync")
    public void processOrderChangeAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderchange_2.OrderChangeType input
    );
}
