package services.oasis.ubl.ordering.orderingprocess.buyerparty.rejectorder;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sat Oct 30 21:01:19 BRST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/rejectOrder", name = "UBL_OrderingProcess_BuyerParty_RejectOrder")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.orderresponse_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class})
public interface UBLOrderingProcessBuyerPartyRejectOrder extends ServiceAccessContract {

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/rejectOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.rejectorder.Alive")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/rejectOrder/alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/rejectOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.rejectorder.AliveResponse")
    public java.lang.Boolean alive();

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "rejectOrder", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/rejectOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.rejectorder.RejectOrder")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/rejectOrder/rejectOrder")
    @ResponseWrapper(localName = "rejectOrderResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/rejectOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.rejectorder.RejectOrderResponse")
    public java.lang.String rejectOrder(
        @WebParam(name = "inputOrderResponseSimple", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.OrderResponseSimpleType inputOrderResponseSimple,
        @WebParam(name = "inputOrderResponse", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponse_2.OrderResponseType inputOrderResponse
    );

    @Oneway
    @RequestWrapper(localName = "rejectOrderAsync", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/rejectOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.rejectorder.RejectOrderAsync")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/rejectOrder/rejectOrderAsync")
    public void rejectOrderAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "inputOrderResponseSimple", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.OrderResponseSimpleType inputOrderResponseSimple,
        @WebParam(name = "inputOrderResponse", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponse_2.OrderResponseType inputOrderResponse
    );
}
