
/*
 * 
 */

package services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.receiveorderitems;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 28 20:49:44 BRT 2018
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_ReceiveOrderItemsService", 
                  wsdlLocation = "file:UBL_FulfilmentWithReceiptAdvice_DeliveryParty_ReceiveOrderItems.wsdl",
                  targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/receiveOrderItems") 
public class UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItemsService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/receiveOrderItems", "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_ReceiveOrderItemsService");
    public final static QName UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItemsServicePort = new QName("http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/receiveOrderItems", "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_ReceiveOrderItemsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:UBL_FulfilmentWithReceiptAdvice_DeliveryParty_ReceiveOrderItems.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:UBL_FulfilmentWithReceiptAdvice_DeliveryParty_ReceiveOrderItems.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItemsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItemsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItemsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItemsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItemsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItemsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItems
     */
    @WebEndpoint(name = "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_ReceiveOrderItemsServicePort")
    public UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItems getUBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItemsServicePort() {
        return super.getPort(UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItemsServicePort, UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItems.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItems
     */
    @WebEndpoint(name = "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_ReceiveOrderItemsServicePort")
    public UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItems getUBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItemsServicePort(WebServiceFeature... features) {
        return super.getPort(UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItemsServicePort, UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItems.class, features);
    }

}
