package services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.receiveorderitems;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 28 20:49:44 BRT 2018
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/receiveOrderItems", name = "UBL_FulfilmentWithReceiptAdvice_DeliveryParty_ReceiveOrderItems")
@XmlSeeAlso({ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.order_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class})
public interface UBLFulfilmentWithReceiptAdviceDeliveryPartyReceiveOrderItems extends ServiceAccessContract {

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/receiveOrderItems/receiveOrderItemsAsync")
    @Oneway
    @RequestWrapper(localName = "receiveOrderItemsAsync", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/receiveOrderItems", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.receiveorderitems.ReceiveOrderItemsAsync")
    public void receiveOrderItemsAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext
    );

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/receiveOrderItems/receiveOrderItems")
    @RequestWrapper(localName = "receiveOrderItems", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/receiveOrderItems", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.receiveorderitems.ReceiveOrderItems")
    @ResponseWrapper(localName = "receiveOrderItemsResponse", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/receiveOrderItems", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.receiveorderitems.ReceiveOrderItemsResponse")
    @WebResult(name = "output", targetNamespace = "")
    public oasis.names.specification.ubl.schema.xsd.order_2.OrderType receiveOrderItems();

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/receiveOrderItems/alive")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/receiveOrderItems", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.receiveorderitems.Alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/deliveryParty/receiveOrderItems", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.deliveryparty.receiveorderitems.AliveResponse")
    @WebResult(name = "output", targetNamespace = "")
    public java.lang.Boolean alive();
}
