package services.oasis.ubl.ordering.orderingprocess.buyerparty.acceptorder;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sat Oct 30 21:01:19 BRST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/acceptOrder", name = "UBL_OrderingProcess_BuyerParty_AcceptOrder")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.orderresponse_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class})
public interface UBLOrderingProcessBuyerPartyAcceptOrder extends ServiceAccessContract {

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/acceptOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.acceptorder.Alive")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/acceptOrder/alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/acceptOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.acceptorder.AliveResponse")
    public java.lang.Boolean alive();

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "acceptOrder", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/acceptOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.acceptorder.AcceptOrder")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/acceptOrder/acceptOrder")
    @ResponseWrapper(localName = "acceptOrderResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/acceptOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.acceptorder.AcceptOrderResponse")
    public java.lang.String acceptOrder(
        @WebParam(name = "inputOrderResponseSimple", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.OrderResponseSimpleType inputOrderResponseSimple,
        @WebParam(name = "inputOrderResponse", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponse_2.OrderResponseType inputOrderResponse
    );

    @Oneway
    @RequestWrapper(localName = "acceptOrderAsync", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/acceptOrder", className = "services.oasis.ubl.ordering.orderingprocess.buyerparty.acceptorder.AcceptOrderAsync")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/buyerParty/acceptOrder/acceptOrderAsync")
    public void acceptOrderAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "inputOrderResponseSimple", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.OrderResponseSimpleType inputOrderResponseSimple,
        @WebParam(name = "inputOrderResponse", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.orderresponse_2.OrderResponseType inputOrderResponse
    );
}
