package services.oasis.ubl.sourcing.catalogueprovision.createcatalogueprocess.providerparty.revisecontent;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sun Oct 31 15:55:48 BRST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/sourcing/catalogueprovision/createcatalogueprocess/providerParty/reviseContent", name = "UBL_CreateCatalogueProcess_ProviderParty_ReviseContent")
@XmlSeeAlso({ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.cataloguerequest_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.catalogue_2.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class})
public interface UBLCreateCatalogueProcessProviderPartyReviseContent extends ServiceAccessContract {

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/sourcing/catalogueprovision/createcatalogueprocess/providerParty/reviseContent", className = "services.oasis.ubl.sourcing.catalogueprovision.createcatalogueprocess.providerparty.revisecontent.Alive")
    @WebMethod(action = "http://ubl.oasis.services/sourcing/catalogueprovision/createcatalogueprocess/providerParty/reviseContent/alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/sourcing/catalogueprovision/createcatalogueprocess/providerParty/reviseContent", className = "services.oasis.ubl.sourcing.catalogueprovision.createcatalogueprocess.providerparty.revisecontent.AliveResponse")
    public java.lang.Boolean alive();

    @Oneway
    @RequestWrapper(localName = "reviseContentAsync", targetNamespace = "http://ubl.oasis.services/sourcing/catalogueprovision/createcatalogueprocess/providerParty/reviseContent", className = "services.oasis.ubl.sourcing.catalogueprovision.createcatalogueprocess.providerparty.revisecontent.ReviseContentAsync")
    @WebMethod(action = "http://ubl.oasis.services/sourcing/catalogueprovision/createcatalogueprocess/providerParty/reviseContent/reviseContentAsync")
    public void reviseContentAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.catalogue_2.CatalogueType input
    );

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "reviseContent", targetNamespace = "http://ubl.oasis.services/sourcing/catalogueprovision/createcatalogueprocess/providerParty/reviseContent", className = "services.oasis.ubl.sourcing.catalogueprovision.createcatalogueprocess.providerparty.revisecontent.ReviseContent")
    @WebMethod(action = "http://ubl.oasis.services/sourcing/catalogueprovision/createcatalogueprocess/providerParty/reviseContent/reviseContent")
    @ResponseWrapper(localName = "reviseContentResponse", targetNamespace = "http://ubl.oasis.services/sourcing/catalogueprovision/createcatalogueprocess/providerParty/reviseContent", className = "services.oasis.ubl.sourcing.catalogueprovision.createcatalogueprocess.providerparty.revisecontent.ReviseContentResponse")
    public oasis.names.specification.ubl.schema.xsd.cataloguerequest_2.CatalogueRequestType reviseContent(
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.catalogue_2.CatalogueType input
    );
}
