package services.oasis.ubl.ordering.orderingprocess.sellerparty.acceptorder;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sat Oct 30 21:02:32 BRST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/acceptOrder", name = "UBL_OrderingProcess_SellerParty_AcceptOrder")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.orderresponse_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.order_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class})
public interface UBLOrderingProcessSellerPartyAcceptOrder extends ServiceAccessContract {

    @Oneway
    @RequestWrapper(localName = "acceptOrderAsync", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/acceptOrder", className = "services.oasis.ubl.ordering.orderingprocess.sellerparty.acceptorder.AcceptOrderAsync")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/acceptOrder/acceptOrderAsync")
    public void acceptOrderAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.order_2.OrderType input
    );

    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/acceptOrder", className = "services.oasis.ubl.ordering.orderingprocess.sellerparty.acceptorder.Alive")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/acceptOrder/alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/acceptOrder", className = "services.oasis.ubl.ordering.orderingprocess.sellerparty.acceptorder.AliveResponse")
    public java.lang.Boolean alive();

    @RequestWrapper(localName = "acceptOrder", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/acceptOrder", className = "services.oasis.ubl.ordering.orderingprocess.sellerparty.acceptorder.AcceptOrder")
    @WebMethod(action = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/acceptOrder/acceptOrder")
    @ResponseWrapper(localName = "acceptOrderResponse", targetNamespace = "http://ubl.oasis.services/ordering/orderingprocess/sellerParty/acceptOrder", className = "services.oasis.ubl.ordering.orderingprocess.sellerparty.acceptorder.AcceptOrderResponse")
    public void acceptOrder(
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.order_2.OrderType input,
        @WebParam(mode = WebParam.Mode.OUT, name = "outputOrderResponse", targetNamespace = "")
        javax.xml.ws.Holder<oasis.names.specification.ubl.schema.xsd.orderresponse_2.OrderResponseType> outputOrderResponse,
        @WebParam(mode = WebParam.Mode.OUT, name = "outputOrderResponseSimple", targetNamespace = "")
        javax.xml.ws.Holder<oasis.names.specification.ubl.schema.xsd.orderresponsesimple_2.OrderResponseSimpleType> outputOrderResponseSimple
    );
}
