package services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.sendordercancellation;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.ufsc.gsigma.infrastructure.ws.access.ServiceAccessContract;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 28 20:49:14 BRT 2018
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/sendOrderCancellation", name = "UBL_FulfilmentWithReceiptAdvice_BuyerParty_SendOrderCancellation")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, un.unece.uncefact.codelist.specification._54217._2001.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.ordercancellation_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.order_2.ObjectFactory.class, br.ufsc.gsigma.processcontext.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class})
public interface UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellation extends ServiceAccessContract {

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/sendOrderCancellation/sendOrderCancellation")
    @RequestWrapper(localName = "sendOrderCancellation", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/sendOrderCancellation", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.sendordercancellation.SendOrderCancellation")
    @ResponseWrapper(localName = "sendOrderCancellationResponse", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/sendOrderCancellation", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.sendordercancellation.SendOrderCancellationResponse")
    @WebResult(name = "output", targetNamespace = "")
    public oasis.names.specification.ubl.schema.xsd.ordercancellation_2.OrderCancellationType sendOrderCancellation(
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.order_2.OrderType input
    );

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/sendOrderCancellation/alive")
    @RequestWrapper(localName = "alive", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/sendOrderCancellation", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.sendordercancellation.Alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/sendOrderCancellation", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.sendordercancellation.AliveResponse")
    @WebResult(name = "output", targetNamespace = "")
    public java.lang.Boolean alive();

    @WebMethod(action = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/sendOrderCancellation/sendOrderCancellationAsync")
    @Oneway
    @RequestWrapper(localName = "sendOrderCancellationAsync", targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/sendOrderCancellation", className = "services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.sendordercancellation.SendOrderCancellationAsync")
    public void sendOrderCancellationAsync(
        @WebParam(name = "processContext", targetNamespace = "")
        br.ufsc.gsigma.processcontext.ProcessContext processContext,
        @WebParam(name = "input", targetNamespace = "")
        oasis.names.specification.ubl.schema.xsd.order_2.OrderType input
    );
}
