
/*
 * 
 */

package services.oasis.ubl.fulfilment.fulfilmentwithreceiptadvice.buyerparty.sendordercancellation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 28 20:49:14 BRT 2018
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "UBL_FulfilmentWithReceiptAdvice_BuyerParty_SendOrderCancellationService", 
                  wsdlLocation = "file:UBL_FulfilmentWithReceiptAdvice_BuyerParty_SendOrderCancellation.wsdl",
                  targetNamespace = "http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/sendOrderCancellation") 
public class UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellationService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/sendOrderCancellation", "UBL_FulfilmentWithReceiptAdvice_BuyerParty_SendOrderCancellationService");
    public final static QName UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellationServicePort = new QName("http://ubl.oasis.services/fulfilment/fulfilmentwithreceiptadvice/buyerParty/sendOrderCancellation", "UBL_FulfilmentWithReceiptAdvice_BuyerParty_SendOrderCancellationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:UBL_FulfilmentWithReceiptAdvice_BuyerParty_SendOrderCancellation.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:UBL_FulfilmentWithReceiptAdvice_BuyerParty_SendOrderCancellation.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellation
     */
    @WebEndpoint(name = "UBL_FulfilmentWithReceiptAdvice_BuyerParty_SendOrderCancellationServicePort")
    public UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellation getUBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellationServicePort() {
        return super.getPort(UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellationServicePort, UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellation
     */
    @WebEndpoint(name = "UBL_FulfilmentWithReceiptAdvice_BuyerParty_SendOrderCancellationServicePort")
    public UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellation getUBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellationServicePort(WebServiceFeature... features) {
        return super.getPort(UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellationServicePort, UBLFulfilmentWithReceiptAdviceBuyerPartySendOrderCancellation.class, features);
    }

}
